set_property SRC_FILE_INFO {cfile:/home/rehan/MERL/FPGA_EMU/FInal_SweRV_on_FPGA_SIMUALED/FInal_SweRV_on_FPGA_SIMUALED.srcs/sources_1/ip/clk_wiz_0_1/clk_wiz_0.xdc rfile:../../../FInal_SweRV_on_FPGA_SIMUALED.srcs/sources_1/ip/clk_wiz_0_1/clk_wiz_0.xdc id:1 order:EARLY scoped_inst:clk_gen/inst} [current_design]
set_property SRC_FILE_INFO {cfile:/home/rehan/MERL/FPGA_EMU/FInal_SweRV_on_FPGA_SIMUALED/FInal_SweRV_on_FPGA_SIMUALED.srcs/constrs_1/imports/new/constraints.xdc rfile:../../../FInal_SweRV_on_FPGA_SIMUALED.srcs/constrs_1/imports/new/constraints.xdc id:2} [current_design]
set_property src_info {type:SCOPED_XDC file:1 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter [get_clocks -of_objects [get_ports clk_in1]] 0.05
set_property src_info {type:XDC file:2 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E19 [get_ports clk_in1]
set_property src_info {type:XDC file:2 line:74 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AM39 [get_ports led_on1]
set_property src_info {type:XDC file:2 line:76 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AN39 [get_ports rst_ind]
set_property src_info {type:XDC file:2 line:78 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AR37 [get_ports porst_ind]
set_property src_info {type:XDC file:2 line:110 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AV39 [get_ports rst]
set_property src_info {type:XDC file:2 line:112 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AR40 [get_ports porst]
