# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param synth.incrementalSynthesisCache ./.Xil/Vivado-2414-kali/incrSyn
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a35ticsg324-1L

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /opt/Xilinx/Vivado/2018.2/bin/Only_SweRV_On_FPGA/Only_SweRV_On_FPGA.cache/wt [current_project]
set_property parent.project_path /opt/Xilinx/Vivado/2018.2/bin/Only_SweRV_On_FPGA/Only_SweRV_On_FPGA.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:arty-a7-35:part0:1.0 [current_project]
set_property ip_output_repo /opt/Xilinx/Vivado/2018.2/bin/Only_SweRV_On_FPGA/Only_SweRV_On_FPGA.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog {
  /opt/Xilinx/Vivado/2018.2/bin/Only_SweRV_On_FPGA/Only_SweRV_On_FPGA.srcs/sources_1/imports/default/common_defines.vh
  /opt/Xilinx/Vivado/2018.2/bin/Only_SweRV_On_FPGA/Only_SweRV_On_FPGA.srcs/sources_1/imports/default/pic_map_auto.h
}
set_property file_type "Verilog Header" [get_files /opt/Xilinx/Vivado/2018.2/bin/Only_SweRV_On_FPGA/Only_SweRV_On_FPGA.srcs/sources_1/imports/default/pic_map_auto.h]
read_mem /opt/Xilinx/Vivado/2018.2/bin/Only_SweRV_On_FPGA/Only_SweRV_On_FPGA.srcs/sources_1/new/program.mem
read_verilog -library xil_defaultlib -sv {
  /opt/Xilinx/Vivado/2018.2/bin/Only_SweRV_On_FPGA/Only_SweRV_On_FPGA.srcs/sources_1/imports/testbench/ahb_sif.sv
  /opt/Xilinx/Vivado/2018.2/bin/Only_SweRV_On_FPGA/Only_SweRV_On_FPGA.srcs/sources_1/imports/design/include/el2_def.sv
  /opt/Xilinx/Vivado/2018.2/bin/Only_SweRV_On_FPGA/Only_SweRV_On_FPGA.srcs/sources_1/imports/design/lib/ahb_to_axi4.sv
  /opt/Xilinx/Vivado/2018.2/bin/Only_SweRV_On_FPGA/Only_SweRV_On_FPGA.srcs/sources_1/imports/design/lib/axi4_to_ahb.sv
  /opt/Xilinx/Vivado/2018.2/bin/Only_SweRV_On_FPGA/Only_SweRV_On_FPGA.srcs/sources_1/imports/testbench/axi_lsu_dma_bridge.sv
  /opt/Xilinx/Vivado/2018.2/bin/Only_SweRV_On_FPGA/Only_SweRV_On_FPGA.srcs/sources_1/imports/lib/beh_lib.sv
  /opt/Xilinx/Vivado/2018.2/bin/Only_SweRV_On_FPGA/Only_SweRV_On_FPGA.srcs/sources_1/imports/design/dmi/dmi_jtag_to_core_sync.v
  /opt/Xilinx/Vivado/2018.2/bin/Only_SweRV_On_FPGA/Only_SweRV_On_FPGA.srcs/sources_1/imports/design/dbg/el2_dbg.sv
  /opt/Xilinx/Vivado/2018.2/bin/Only_SweRV_On_FPGA/Only_SweRV_On_FPGA.srcs/sources_1/imports/design/dec/el2_dec.sv
  /opt/Xilinx/Vivado/2018.2/bin/Only_SweRV_On_FPGA/Only_SweRV_On_FPGA.srcs/sources_1/imports/design/dec/el2_dec_decode_ctl.sv
  /opt/Xilinx/Vivado/2018.2/bin/Only_SweRV_On_FPGA/Only_SweRV_On_FPGA.srcs/sources_1/imports/design/dec/el2_dec_gpr_ctl.sv
  /opt/Xilinx/Vivado/2018.2/bin/Only_SweRV_On_FPGA/Only_SweRV_On_FPGA.srcs/sources_1/imports/design/dec/el2_dec_ib_ctl.sv
  /opt/Xilinx/Vivado/2018.2/bin/Only_SweRV_On_FPGA/Only_SweRV_On_FPGA.srcs/sources_1/imports/design/dec/el2_dec_tlu_ctl.sv
  /opt/Xilinx/Vivado/2018.2/bin/Only_SweRV_On_FPGA/Only_SweRV_On_FPGA.srcs/sources_1/imports/design/dec/el2_dec_trigger.sv
  /opt/Xilinx/Vivado/2018.2/bin/Only_SweRV_On_FPGA/Only_SweRV_On_FPGA.srcs/sources_1/imports/design/el2_dma_ctrl.sv
  /opt/Xilinx/Vivado/2018.2/bin/Only_SweRV_On_FPGA/Only_SweRV_On_FPGA.srcs/sources_1/imports/design/exu/el2_exu.sv
  /opt/Xilinx/Vivado/2018.2/bin/Only_SweRV_On_FPGA/Only_SweRV_On_FPGA.srcs/sources_1/imports/design/exu/el2_exu_alu_ctl.sv
  /opt/Xilinx/Vivado/2018.2/bin/Only_SweRV_On_FPGA/Only_SweRV_On_FPGA.srcs/sources_1/imports/design/exu/el2_exu_div_ctl.sv
  /opt/Xilinx/Vivado/2018.2/bin/Only_SweRV_On_FPGA/Only_SweRV_On_FPGA.srcs/sources_1/imports/design/exu/el2_exu_mul_ctl.sv
  /opt/Xilinx/Vivado/2018.2/bin/Only_SweRV_On_FPGA/Only_SweRV_On_FPGA.srcs/sources_1/imports/design/ifu/el2_ifu.sv
  /opt/Xilinx/Vivado/2018.2/bin/Only_SweRV_On_FPGA/Only_SweRV_On_FPGA.srcs/sources_1/imports/design/ifu/el2_ifu_aln_ctl.sv
  /opt/Xilinx/Vivado/2018.2/bin/Only_SweRV_On_FPGA/Only_SweRV_On_FPGA.srcs/sources_1/imports/design/ifu/el2_ifu_bp_ctl.sv
  /opt/Xilinx/Vivado/2018.2/bin/Only_SweRV_On_FPGA/Only_SweRV_On_FPGA.srcs/sources_1/imports/design/ifu/el2_ifu_compress_ctl.sv
  /opt/Xilinx/Vivado/2018.2/bin/Only_SweRV_On_FPGA/Only_SweRV_On_FPGA.srcs/sources_1/imports/design/ifu/el2_ifu_ic_mem.sv
  /opt/Xilinx/Vivado/2018.2/bin/Only_SweRV_On_FPGA/Only_SweRV_On_FPGA.srcs/sources_1/imports/design/ifu/el2_ifu_iccm_mem.sv
  /opt/Xilinx/Vivado/2018.2/bin/Only_SweRV_On_FPGA/Only_SweRV_On_FPGA.srcs/sources_1/imports/design/ifu/el2_ifu_ifc_ctl.sv
  /opt/Xilinx/Vivado/2018.2/bin/Only_SweRV_On_FPGA/Only_SweRV_On_FPGA.srcs/sources_1/imports/design/ifu/el2_ifu_mem_ctl.sv
  /opt/Xilinx/Vivado/2018.2/bin/Only_SweRV_On_FPGA/Only_SweRV_On_FPGA.srcs/sources_1/imports/lib/el2_lib.sv
  /opt/Xilinx/Vivado/2018.2/bin/Only_SweRV_On_FPGA/Only_SweRV_On_FPGA.srcs/sources_1/imports/design/lsu/el2_lsu.sv
  /opt/Xilinx/Vivado/2018.2/bin/Only_SweRV_On_FPGA/Only_SweRV_On_FPGA.srcs/sources_1/imports/design/lsu/el2_lsu_addrcheck.sv
  /opt/Xilinx/Vivado/2018.2/bin/Only_SweRV_On_FPGA/Only_SweRV_On_FPGA.srcs/sources_1/imports/design/lsu/el2_lsu_bus_buffer.sv
  /opt/Xilinx/Vivado/2018.2/bin/Only_SweRV_On_FPGA/Only_SweRV_On_FPGA.srcs/sources_1/imports/design/lsu/el2_lsu_bus_intf.sv
  /opt/Xilinx/Vivado/2018.2/bin/Only_SweRV_On_FPGA/Only_SweRV_On_FPGA.srcs/sources_1/imports/design/lsu/el2_lsu_clkdomain.sv
  /opt/Xilinx/Vivado/2018.2/bin/Only_SweRV_On_FPGA/Only_SweRV_On_FPGA.srcs/sources_1/imports/design/lsu/el2_lsu_dccm_ctl.sv
  /opt/Xilinx/Vivado/2018.2/bin/Only_SweRV_On_FPGA/Only_SweRV_On_FPGA.srcs/sources_1/imports/design/lsu/el2_lsu_dccm_mem.sv
  /opt/Xilinx/Vivado/2018.2/bin/Only_SweRV_On_FPGA/Only_SweRV_On_FPGA.srcs/sources_1/imports/design/lsu/el2_lsu_ecc.sv
  /opt/Xilinx/Vivado/2018.2/bin/Only_SweRV_On_FPGA/Only_SweRV_On_FPGA.srcs/sources_1/imports/design/lsu/el2_lsu_lsc_ctl.sv
  /opt/Xilinx/Vivado/2018.2/bin/Only_SweRV_On_FPGA/Only_SweRV_On_FPGA.srcs/sources_1/imports/design/lsu/el2_lsu_stbuf.sv
  /opt/Xilinx/Vivado/2018.2/bin/Only_SweRV_On_FPGA/Only_SweRV_On_FPGA.srcs/sources_1/imports/design/lsu/el2_lsu_trigger.sv
  /opt/Xilinx/Vivado/2018.2/bin/Only_SweRV_On_FPGA/Only_SweRV_On_FPGA.srcs/sources_1/imports/design/el2_mem.sv
  /opt/Xilinx/Vivado/2018.2/bin/Only_SweRV_On_FPGA/Only_SweRV_On_FPGA.srcs/sources_1/imports/design/el2_pic_ctrl.sv
  /opt/Xilinx/Vivado/2018.2/bin/Only_SweRV_On_FPGA/Only_SweRV_On_FPGA.srcs/sources_1/imports/design/el2_swerv.sv
  /opt/Xilinx/Vivado/2018.2/bin/Only_SweRV_On_FPGA/Only_SweRV_On_FPGA.srcs/sources_1/imports/design/el2_swerv_wrapper.sv
  /opt/Xilinx/Vivado/2018.2/bin/Only_SweRV_On_FPGA/Only_SweRV_On_FPGA.srcs/sources_1/imports/design/lib/mem_lib.sv
  /opt/Xilinx/Vivado/2018.2/bin/Only_SweRV_On_FPGA/Only_SweRV_On_FPGA.srcs/sources_1/imports/lib/mem_lib.sv
  /opt/Xilinx/Vivado/2018.2/bin/Only_SweRV_On_FPGA/Only_SweRV_On_FPGA.srcs/sources_1/imports/design/dmi/rvjtag_tap.v
  /opt/Xilinx/Vivado/2018.2/bin/Only_SweRV_On_FPGA/Only_SweRV_On_FPGA.srcs/sources_1/imports/testbench/tb_top.sv
}
read_verilog -library xil_defaultlib /opt/Xilinx/Vivado/2018.2/bin/Only_SweRV_On_FPGA/Only_SweRV_On_FPGA.srcs/sources_1/imports/design/dmi/dmi_wrapper.v
read_ip -quiet /opt/Xilinx/Vivado/2018.2/bin/Only_SweRV_On_FPGA/Only_SweRV_On_FPGA.srcs/sources_1/ip/clk_wiz_0_1/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all /opt/Xilinx/Vivado/2018.2/bin/Only_SweRV_On_FPGA/Only_SweRV_On_FPGA.srcs/sources_1/ip/clk_wiz_0_1/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all /opt/Xilinx/Vivado/2018.2/bin/Only_SweRV_On_FPGA/Only_SweRV_On_FPGA.srcs/sources_1/ip/clk_wiz_0_1/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all /opt/Xilinx/Vivado/2018.2/bin/Only_SweRV_On_FPGA/Only_SweRV_On_FPGA.srcs/sources_1/ip/clk_wiz_0_1/clk_wiz_0_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /opt/Xilinx/Vivado/2018.2/bin/Only_SweRV_On_FPGA/Only_SweRV_On_FPGA.srcs/constrs_1/imports/new/constraints.xdc
set_property used_in_implementation false [get_files /opt/Xilinx/Vivado/2018.2/bin/Only_SweRV_On_FPGA/Only_SweRV_On_FPGA.srcs/constrs_1/imports/new/constraints.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top tb_top -part xc7a35ticsg324-1L


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef tb_top.dcp
create_report "synth_2_synth_report_utilization_0" "report_utilization -file tb_top_utilization_synth.rpt -pb tb_top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
